### ISSUE TITLE
When should drain handlers run?

### ISSUE THREAD

**Issue by jschaf** [jrockway/opinionated-server#10]
First off, loving this template. It's a nice production server with all sorts of goodies.

Regarding `AddDrainHandler`: the doc states:

> It is not safe to call while ListenAndServe is running

But the drain handlers run before the non-debug HTTP server shutdown. https://github.com/jrockway/opinionated-server/blob/337adb03a93f8891d6bd06760191a8ad51eda1d5/server/server.go#L510

My guess is the docs are misleading. Presumably, you want the drain handlers to run before the server completely shuts down.

**Comment by jrockway** [comment]
Thanks for taking a look!

I think the comment is just trying to say that adding new handlers while servers are running is unsafe.  It would be unsafe to add drain handlers while ListenAndServe is running because the read and write to drainHandlers could contend under circumstances that the caller can't control (usually doneCh being "done" and the servers closing before you have a chance to add one).

You're responsible for the thread safety of the handlers.  (Typically I just close a channel there, and then in long-running requests write something like `select { case <-drainCh: return errors.New("draining"); case <-ctx.Done(): return ctx.Err(); case <-workToDo: doWork() }`)

I'm going to clean up that documentation to talk about the difference between the safety of calling `AddDrainHandler` vs. the safety of the function you pass in.

**Comment by jrockway** [comment]
Attempted to improve the documentation here.  Please reopen if you disagree with anything or it's still not clear :)
